linters:
  enable-all: false
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    ## - execinquery
    - exhaustive
    - copyloopvar # Ersetzt exportloopref
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113 # Ersetzt goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - mnd # Ersetzt gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    # - rowserrcheck
    # - sqlclosecheck
    # - structcheck
    - stylecheck
    - tagliatelle
    - usetesting # Ersetzt tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    # - wastedassign
    - whitespace
    - wsl
  fast: false
  # disable:
    # - execinquery  # Deaktivierter Linter, nicht mehr vorhanden
run:
  timeout: 3m
  go: "1.24"  # Hier die Go-Version setzen

linters-settings:
  gofumpt:
    extra-rules: true

